name: Stats

on: 
  push:
    branches: [ main ]
    
jobs:  
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
          
    steps:
      - name: Checkout Repo V4
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Script
        run: python .Testing/stats.py
      
      - name: Commit and Push Change
        uses: stefanzweifel/git-auto-commit-action@v6
        with: 
          commit_message: Update stats
          commit_user_name: Mauricio Garay V. [Github Actions]
          commit_user_email: laloaggro@gmail.com
          commit_author: laloaggro
